const actionsTypes = {
	RESET_GAME: "RESET_GAME",
	CARD_FOR_PLAYER: "CARD_FOR_PLAYER",
	IS_PLAYER_DONE: "IS_PLAYER_DONE",
	PLAYER_IS_DONE: "PLAYER_IS_DONE",
	DRAW_CARDS_FOR_DEALER: "DRAW_CARDS_FOR_DEALER",
	FIND_WINNER: "FIND_WINNER",
};

export default actionsTypes;
